### ISSUE TITLE
java.nio.channels.ClosedChannelException when force refresh Chrome with open websockets connection

### ISSUE THREAD

**Issue by doitian** [Kotlin/ktor#106]
The exception `java.nio.channels.ClosedChannelException` is uncaught, and `ktor-websockets` on close handler is not invoked when use `ktor-netty` and `ktor-websockets` together.

Steps to reproduce:

- Setup a websockets endpoint.
- Connect in the browser, then hold shift to force refresh browser.
- Exception is thrown, on close handler is not invoked.

`ktor-jetty` has no such issue.

**Comment by pevdh** [comment]
Any update on this bug? Is this a Netty issue or is it fixable by Ktor?

**Comment by cy6erGn0m** [comment]
I think it should be fixed in master, I don't see this error under Linux anymore but I haven't tested in on windows yet (it could work different under different OS)

**Comment by doitian** [comment]
I'm using macOS, I'll try master today.

**Comment by doitian** [comment]
WebSockets changed a log in master. Now the issue cannot be reproduce but I found new bugs. WebSocket seems broken when using Safari.

When using Netty, the close handler is never invoked. The line https://github.com/doitian/KtorNettyWebsocket/blob/master/src/main/kotlin/me/iany/KtorNettyWebsocket.kt#L29 is never reached when the socket is created in Safari.

When using Jetty, sometimes it is OK. But sometimes it throws exception. And if so, the finally clause will be invoked about 2 seconds later after refresh browser.

The thrown exception:

```
Exception in thread "qtp977993101-16" kotlinx.coroutines.experimental.channels.ClosedReceiveChannelException: Channel was closed
Frame TEXT (fin=true, buffer len = 5)
	at kotlinx.coroutines.experimental.channels.Closed.getReceiveException(AbstractChannel.kt:919)
	at kotlinx.coroutines.experimental.channels.AbstractChannel.receiveResult(AbstractChannel.kt:475)
	at kotlinx.coroutines.experimental.channels.AbstractChannel.receive(AbstractChannel.kt:468)
	at kotlinx.coroutines.experimental.channels.ChannelCoroutine.receive(ChannelCoroutine.kt)
	at org.jetbrains.ktor.websocket.PingPongKt$pinger$j$1$1.doResume(PingPong.kt:41)
	at org.jetbrains.ktor.websocket.PingPongKt$pinger$j$1$1.invoke(PingPong.kt)
	at org.jetbrains.ktor.websocket.PingPongKt$pinger$j$1$1.invoke(PingPong.kt)
	at kotlinx.coroutines.experimental.ScheduledKt.withTimeoutOrNull(Scheduled.kt:148)
	at org.jetbrains.ktor.websocket.PingPongKt$pinger$j$1.doResume(PingPong.kt:39)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:235)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cy6erGn0m** [comment]
Looks like Safari doesn't send close frame while we are unable to detect closed channel for some reason this is why it doesn't get closed until timeout

**Comment by cy6erGn0m** [comment]
Notice that server generally can't detect closed connection immediately in many cases and some delay is just fine

**Comment by cy6erGn0m** [comment]
@doitian  Just pushed few relevant changes so should work better now

**Comment by doitian** [comment]
Tried again and worked. I'm afraid my Safari is broken.I'm OK to close this.
