### ISSUE TITLE
Internal Server Error when invalid Session-ID is sent by the client

### ISSUE THREAD

**Issue by d3xter** [Kotlin/ktor#128]
embeddedServer(Netty, port, host) {
        withSessions(SessionConfigBuilder(User::class).apply {
            withCookieBySessionId(inMemorySessionStorage()) {

     
                serializer = object : SessionSerializer<User> {
                    [...]
                }
            }
        }.build())

        routing {
            get("/") {
                it.respond("Hello World")
            }
    }.start(wait = true)

This is a small example of my Netty-Server. When requesting "/" without any Session-ID-Cookie it works fine, but when the client sends a random Session-ID, an IllegalArgumentException is thrown, even without retrieving the Session-Object.

    ERROR ktor.application - Unhandled: GET - /
    java.lang.IllegalArgumentException: Session 8036a01f7871e5454b6fb6fc3163a1cab25067b14808a53f78e9bc35426079a0 not found
	at org.jetbrains.ktor.sessions.InMemorySessionStorage$read$1.doResume(InMemorySessionStorage.kt:16)
	at org.jetbrains.ktor.sessions.InMemorySessionStorage.read(InMemorySessionStorage.kt)
	at org.jetbrains.ktor.sessions.CookieByIdSessionTracker$lookup$1.doResume(ServerSessions.kt:57)
	at org.jetbrains.ktor.sessions.CookieByIdSessionTracker.lookup(ServerSessions.kt)
	at org.jetbrains.ktor.sessions.SessionsKt$withSessions$1.doResume(Sessions.kt:59)
	at org.jetbrains.ktor.sessions.SessionsKt$withSessions$1.invoke(Sessions.kt)
	at org.jetbrains.ktor.sessions.SessionsKt$withSessions$1.invoke(Sessions.kt)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:26)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt)
	at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:21)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.doResume(DefaultHostPipeline.kt:20)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.invoke(DefaultHostPipeline.kt)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.invoke(DefaultHostPipeline.kt)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:26)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt)
	at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:21)
	at org.jetbrains.ktor.netty.NettyApplicationCallHandler$channelRead0$1.doResume(NettyApplicationCallHandler.kt:9)
	at org.jetbrains.ktor.netty.NettyApplicationCallHandler$channelRead0$1.invoke(NettyApplicationCallHandler.kt)
	at org.jetbrains.ktor.netty.NettyApplicationCallHandler$channelRead0$1.invoke(NettyApplicationCallHandler.kt:6)
	at org.jetbrains.ktor.pipeline.AsyncKt$launchAsync$1.doResume(Async.kt:10)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:152)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cy6erGn0m** [comment]
Fixed, will be shipped with 0.3.3
