### ISSUE TITLE
Exceptions when pushing big packet to socket

### ISSUE THREAD

**Issue by serjic** [Kotlin/ktor#135]
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.jetbrains.ktor.jetty.EndPointWriteChannel.write(EndPointWriteChannel.kt:32)
	at org.jetbrains.ktor.websocket.WebSocketWriter$drainQueueAndSerialize$1.doResume(WebSocketWriter.kt:81)
	at org.jetbrains.ktor.websocket.WebSocketWriter.drainQueueAndSerialize(WebSocketWriter.kt)
Exception in thread "qtp1739876329-13" org.eclipse.jetty.io.EofException
	at org.jetbrains.ktor.websocket.WebSocketWriter.access$drainQueueAndSerialize(WebSocketWriter.kt:10)
	at org.jetbrains.ktor.websocket.WebSocketWriter$writeLoop$1.doResume(WebSocketWriter.kt:37)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:235)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:270)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	... 13 common frames omitted
2017-06-23 11:39:31.409 [qtp1739876329-13] INFO  kserver/WS.kt - Connection closed 6w61m1egvt
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.jetbrains.ktor.jetty.EndPointWriteChannel.write(EndPointWriteChannel.kt:32)
	at org.jetbrains.ktor.websocket.WebSocketWriter$drainQueueAndSerialize$1.doResume(WebSocketWriter.kt:81)
	at org.jetbrains.ktor.websocket.WebSocketWriter.drainQueueAndSerialize(WebSocketWriter.kt)
	at org.jetbrains.ktor.websocket.WebSocketWriter.access$drainQueueAndSerialize(WebSocketWriter.kt:10)
	at org.jetbrains.ktor.websocket.WebSocketWriter$writeLoop$1.doResume(WebSocketWriter.kt:37)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:235)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:270)
	... 13 more

**Comment by cy6erGn0m** [comment]
Who is client? Does it have frame size limit? Can you observe `closeReason` after the error ?

**Comment by cy6erGn0m** [comment]
Fixed in master, to be shipped with 0.3.4

**Comment by cy6erGn0m** [comment]
Only affects frames with size in range 32768 .. 65535
