### ISSUE TITLE
maven install error - ktor samples

### ISSUE THREAD

**Issue by rakshakhegde** [Kotlin/ktor#140]
I'm running [ktor-samples](https://github.com/Kotlin/ktor/tree/master/ktor-samples) on Ubuntu server. On running `maven install`, I'm getting this error in the end:
```
[ERROR] Failed to execute goal on project ktor-samples: Could not resolve dependencies for project org.jetbrains.ktor:ktor-samples:pom:0.4.0-SNAPSHOT: The following artifacts could not be resolved: org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Is there something I'm missing? I'm unable to run the sample projects.

**Comment by rakshakhegde** [comment]
Update: With error stacktraces on: `mvn install -e`

Output:
```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-hello:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-html:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-locations:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-auth:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-async:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-testable:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-json:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-post:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-embedded:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-httpbin:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:you-kube:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:kweet:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-websocket:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-ssl-http2:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples-custom-feature:jar:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jetbrains.ktor:ktor-samples:pom:0.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.jetbrains.ktor:ktor-samples:[unknown-version], /root/projects/ktor/ktor-samples/pom.xml, line 66, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ktor-samples
[INFO] ktor-samples-hello
[INFO] ktor-samples-html
[INFO] ktor-samples-locations
[INFO] ktor-samples-auth
[INFO] ktor-samples-async
[INFO] ktor-samples-testable
[INFO] ktor-samples-json
[INFO] ktor-samples-post
[INFO] ktor-samples-embedded
[INFO] ktor-samples-httpbin
[INFO] you-kube
[INFO] kweet
[INFO] ktor-samples-websocket
[INFO] ktor-samples-ssl-http2
[INFO] ktor-samples-custom-feature
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ktor-samples 0.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ktor-samples ....................................... FAILURE [  0.609 s]
[INFO] ktor-samples-hello ................................. SKIPPED
[INFO] ktor-samples-html .................................. SKIPPED
[INFO] ktor-samples-locations ............................. SKIPPED
[INFO] ktor-samples-auth .................................. SKIPPED
[INFO] ktor-samples-async ................................. SKIPPED
[INFO] ktor-samples-testable .............................. SKIPPED
[INFO] ktor-samples-json .................................. SKIPPED
[INFO] ktor-samples-post .................................. SKIPPED
[INFO] ktor-samples-embedded .............................. SKIPPED
[INFO] ktor-samples-httpbin ............................... SKIPPED
[INFO] you-kube ........................................... SKIPPED
[INFO] kweet .............................................. SKIPPED
[INFO] ktor-samples-websocket ............................. SKIPPED
[INFO] ktor-samples-ssl-http2 ............................. SKIPPED
[INFO] ktor-samples-custom-feature ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.433 s
[INFO] Finished at: 2017-07-09T07:10:44+00:00
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ktor-samples: Could not resolve dependencies for project org.jetbrains.ktor:ktor-samples:pom:0.4.0-SNAPSHOT: The following artifacts could not be resolved: org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ktor-samples: Could not resolve dependencies for project org.jetbrains.ktor:ktor-samples:pom:0.4.0-SNAPSHOT: The following artifacts could not be resolved: org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.jetbrains.ktor:ktor-samples:pom:0.4.0-SNAPSHOT: The following artifacts could not be resolved: org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:212)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-jetty:jar:0.4.0-SNAPSHOT, org.jetbrains.ktor:ktor-netty:jar:0.4.0-SNAPSHOT: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.jetbrains.ktor:ktor-core:jar:0.4.0-SNAPSHOT in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by orangy** [comment]
Do you run `mvn install` from the ktor root directory?

**Comment by rakshakhegde** [comment]
Yeah I did that and it worked. But I want to run only a sample project in isolation and build off of that as a base for my personal repo. So, how to get that working?

**Comment by orangy** [comment]
Please setup your project as described here: https://github.com/Kotlin/ktor#maven
