### ISSUE TITLE
Async sample fails: Response has already been sent

### ISSUE THREAD

**Issue by dinomite** [Kotlin/ktor#142]
I run the `AsyncApplication` sample using the included IntelliJ Jetty configuration.  The log from startup through the first request:

    Connected to the target VM, address: '127.0.0.1:59002', transport: 'socket'
    2017-07-09 13:51:20.757 [main] TRACE Application - {
        # application.conf @ file:/Users/dinomite/Seafile/code/misc/ktor/ktor-samples/ktor-samples-async/target/classes/application.conf: 6
        "application" : {
            # application.conf @ file:/Users/dinomite/Seafile/code/misc/ktor/ktor-samples/ktor-samples-async/target/classes/application.conf: 7
            "modules" : [
                # application.conf @ file:/Users/dinomite/Seafile/code/misc/ktor/ktor-samples/ktor-samples-async/target/classes/application.conf: 7
                "org.jetbrains.ktor.samples.async.AsyncApplicationKt.main"
            ]
        },
        # application.conf @ file:/Users/dinomite/Seafile/code/misc/ktor/ktor-samples/ktor-samples-async/target/classes/application.conf: 2
        "deployment" : {
            # application.conf @ file:/Users/dinomite/Seafile/code/misc/ktor/ktor-samples/ktor-samples-async/target/classes/application.conf: 3
            "port" : 8080
        },
        # Content hidden
        "security" : "***"
    }

    2017-07-09 13:51:20.926 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1064ms to org.eclipse.jetty.util.log.Slf4jLog
    2017-07-09 13:51:21.170 [main] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
    2017-07-09 13:51:22.367 [main] TRACE Application - Application started: org.jetbrains.ktor.application.Application@3b220bcb
    2017-07-09 13:51:22.371 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.1.v20170120
    2017-07-09 13:51:22.460 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@165b2f7f{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8080}
    2017-07-09 13:51:22.461 [main] INFO  org.eclipse.jetty.server.Server - Started @2604ms
    2017-07-09 13:51:24.539 [pool-1-thread-1 @coroutine#1] TRACE Application - Unhandled: GET - /
    Exception in thread "ForkJoinPool.commonPool-worker-1 @coroutine#2" java.lang.IllegalStateException: Response has already been sent
        at org.jetbrains.ktor.host.BaseApplicationCall$$special$$inlined$apply$lambda$1.doResume(BaseApplicationCall.kt:25)
        at org.jetbrains.ktor.host.BaseApplicationCall$$special$$inlined$apply$lambda$1.invoke(BaseApplicationCall.kt)
        at org.jetbrains.ktor.host.BaseApplicationCall$$special$$inlined$apply$lambda$1.invoke(BaseApplicationCall.kt:12)
        at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)
        at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt)
        at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
        at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt$respond$1.doResume(ApplicationResponseFunctions.kt:11)
        at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt.respond(ApplicationResponseFunctions.kt)
        at org.jetbrains.ktor.html.RespondHtmlKt$respondHtml$1.doResume(RespondHtml.kt:12)
        at org.jetbrains.ktor.html.RespondHtmlKt.respondHtml(RespondHtml.kt)
        at org.jetbrains.ktor.html.RespondHtmlKt.respondHtml$default(RespondHtml.kt:11)
        at org.jetbrains.ktor.samples.async.AsyncApplicationKt$handleLongCalculation$1.doResume(AsyncApplication.kt:35)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:235)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Other sample applications work for me out of the box.

**Comment by rakshakhegde** [comment]
@orangy Why was this closed? Even I had the same issue.

**Comment by dinomite** [comment]
@rakshakhegde The commit by @orangy solved the issue.

**Comment by kosiakk** [comment]
Well, I have a very similar error in ktor 0.4.0-alpha-14, and in totally different situations:
1. I get tons of such errors, if I refresh page quickly enough - to cancel previous requests
2. If the app was _sleeping for a long time_, sometimes, one of the first page-requests (with css or js) fails and Chrome is "waiting" for data forever. 

There are no my classes in the stack trace - the app returns `ResourceFileContent` back to KTOR to compress and send out (with a E-tag and cache instructions). Browser request is not aborted in this case, it just stalls.

```
Exception in thread "nettyCallPool-4-1" java.lang.IllegalStateException: Response has already been sent
	at org.jetbrains.ktor.host.BaseApplicationResponse$$special$$inlined$apply$lambda$1.doResume(BaseApplicationResponse.kt:30)
	at org.jetbrains.ktor.host.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt)
	at org.jetbrains.ktor.host.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt:14)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:21)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceedWith(PipelineContext.kt:18)
	at org.jetbrains.ktor.features.Compression$interceptor$1.doResume(Compression.kt:100)
	at org.jetbrains.ktor.features.Compression.interceptor(Compression.kt:54)
	at org.jetbrains.ktor.features.Compression.access$interceptor(Compression.kt:50)
	at org.jetbrains.ktor.features.Compression$Feature$install$1.doResume(Compression.kt:143)
	at org.jetbrains.ktor.features.Compression$Feature$install$1.invoke(Compression.kt)
	at org.jetbrains.ktor.features.Compression$Feature$install$1.invoke(Compression.kt:132)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:21)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceedWith(PipelineContext.kt:18)
	at org.jetbrains.ktor.host.DefaultTransformKt$installDefaultTransformations$1.doResume(DefaultTransform.kt:37)
	at org.jetbrains.ktor.host.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at org.jetbrains.ktor.host.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:21)
	at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:17)
	at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt$respond$1.doResume(ApplicationResponseFunctions.kt:12)
	at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt.respond(ApplicationResponseFunctions.kt:11)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.doResume(DefaultHostPipeline.kt:31)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.invoke(DefaultHostPipeline.kt)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.invoke(DefaultHostPipeline.kt)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:21)
	at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:17)
	at org.jetbrains.ktor.pipeline.PipelineKt.execute(Pipeline.kt:145)
	at org.jetbrains.ktor.netty.NettyApplicationCallHandler$handleRequest$1.doResume(NettyApplicationCallHandler.kt:21)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by orangy** [comment]
@kosiakk do I understand it correctly that you have just a simple `static` section with a (html?) file and compression enabled?

**Comment by orangy** [comment]
Okay, I think I reproduced it. The problem is pretty simple, while sending a response an exception (IOException: Broken Pipe) occurred because client closed connection. Instead of cancelling pipeline in a proper way we assume that there is a problem in the code and try to respond with (500 Internal Server Error), and this fails again, because headers has already been sent.

**Comment by kosiakk** [comment]
Yes, it can be reduced to

```
install(ConditionalHeaders)
install(Compression)
install(CacheControl) {
    maxAgeSeconds = 20 * 60
}
...
get("/") {

   val folder = "public"
   static(folder) {
      resources(folder)
   }
}
```
where CacheControl just adds `MaxAge` to all outgoing `ResourceFileContent` and `LocalFileContent`.
