### ISSUE TITLE
StatusPages cause a reponse sent exception

### ISSUE THREAD

**Issue by ian4hu** [Kotlin/ktor#201]
Only install one feature can re-produce it

```kotlin
    install(StatusPages) {
        statusFile(HttpStatusCode.NotFound, filePattern = "error-#.html")
    }
```

the StatusPages feature cause a reponse sent exception 

```text
Exception in thread "nettyCallPool-4-1" java.lang.IllegalStateException: Response has already been sent
	at org.jetbrains.ktor.host.BaseApplicationResponse$$special$$inlined$apply$lambda$1.doResume(BaseApplicationResponse.kt:30)
	at org.jetbrains.ktor.host.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt)
	at org.jetbrains.ktor.host.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt:14)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:29)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceedWith(PipelineContext.kt:18)
	at org.jetbrains.ktor.host.DefaultTransformKt$installDefaultTransformations$1.doResume(DefaultTransform.kt:37)
	at org.jetbrains.ktor.host.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at org.jetbrains.ktor.host.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:29)
	at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:17)
	at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt.respond(ApplicationResponseFunctions.kt:12)
	at org.jetbrains.ktor.host.DefaultHostPipelineKt$defaultHostPipeline$2.doResume(DefaultHostPipeline.kt:34)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:60)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:59)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:59)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:59)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by orangy** [comment]
Duplicates #196
