### ISSUE TITLE
Exception when browser tab with active Websocket connection was closed

### ISSUE THREAD

**Issue by fluidsonic** [Kotlin/ktor#202]
I have a Websocket like this:

```kotlin
webSocket {
	println("connected")

	try {
		incoming.consumeEach { frame ->
			if (frame is Frame.Text) {
				val message = frame.readText()
				println("message: $message")
			}
		}
	}
	finally {
		println("gone")
	}
}
```

I'm running this on localhost on macOS and a tab in Chrome connects to that Websocket on localhost.

When I close the browser tab, "gone" is properly logged but few seconds later I get an exception:

```
Exception in thread "nettyWorkerPool-3-2" org.jetbrains.ktor.cio.ChannelWriteException: Write operation future failed
	at org.jetbrains.ktor.netty.CIOKt$wrappingErrorHandler$1.invoke(CIO.kt:21)
	at org.jetbrains.ktor.netty.CIOKt$wrappingErrorHandler$1.invoke(CIO.kt)
	at org.jetbrains.ktor.netty.CoroutineListener.operationComplete(CIO.kt:63)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:906)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:791)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1291)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.timeout.WriteTimeoutHandler.write(WriteTimeoutHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1089)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1136)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1078)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
```

So ktor is trying to send something on a closed channel.

I see that this code is invoked which may cause the error:
https://github.com/Kotlin/ktor/blob/1909e9bae7b831920329aec138d6e63a3ca707a2/ktor-features/ktor-websockets/src/org/jetbrains/ktor/websocket/CloseSequence.kt#L28-L31

So probably either the server shouldn't send a close event when it received a close event from the client or it should not log that exception in that particular scenario.

ktor 0.4.0

**Comment by cy6erGn0m** [comment]
According to the specification, websocket peer should always respond to close frame with close echo (so browser SHOULD NOT close connection until it get close response received however it does so). So the right choice here is to avoid logging in "close sequence" at premature closed channel.

**Comment by cy6erGn0m** [comment]
Should be fixed in master. @fluidsonic could you please verify?

**Comment by fluidsonic** [comment]
I can confirm that an exception is no longer logged with 76616bf 👍 
Thank you!
