### ISSUE TITLE
LinkageError when the path matches ...

### ISSUE THREAD

**Issue by devulex** [Kotlin/ktor#218]
Take again, as an example, [kotlin-fullstack-sample](https://github.com/Kotlin/kotlin-fullstack-sample) (Thinkter)

Adding tasks to copy jars:
```gradle
task install(type: Copy) {
    dependsOn build
    from configurations.runtime
    from jar
    into "${project.projectDir}/lib"
}
```
Execute the task and run the backend:
```
java -cp "lib/backend-0.0.1-SNAPSHOT.jar;lib/*" org.jetbrains.ktor.jetty.DevelopmentHost`
```
Full path: `D:\kotlin-fullstack-sample\lib`
Backend was successfully started.

But if you just change `kotlin-fullstack-sample` to `thinkter` and the server does not start:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at kotlin.reflect.jvm.internal.FunctionCaller$Method.callMethod(FunctionCaller.kt:98)
        at kotlin.reflect.jvm.internal.FunctionCaller$StaticMethod.call(FunctionCaller.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(KCallableImpl.kt:147)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
        at org.jetbrains.ktor.host.ApplicationLoader.callEntryPointFunction(ApplicationLoader.kt:257)
        at org.jetbrains.ktor.host.ApplicationLoader.instantiateAndConfigure(ApplicationLoader.kt:228)
        at org.jetbrains.ktor.host.ApplicationLoader.instantiateAndConfigureApplication(ApplicationLoader.kt:189)
        at org.jetbrains.ktor.host.ApplicationLoader.createApplication(ApplicationLoader.kt:107)
        at org.jetbrains.ktor.host.ApplicationLoader.getApplication(ApplicationLoader.kt:60)
        at org.jetbrains.ktor.host.ApplicationLifecycle$DefaultImpls.ensureApplication(ApplicationLifecycle.kt:22)
        at org.jetbrains.ktor.host.ApplicationLoader.ensureApplication(ApplicationLoader.kt:22)
        at org.jetbrains.ktor.jetty.JettyApplicationHost.start(JettyApplicationHost.kt:164)
        at org.jetbrains.ktor.jetty.JettyApplicationHost.start(JettyApplicationHost.kt:27)
        at org.jetbrains.ktor.host.ApplicationHostStartable$DefaultImpls.start$default(ApplicationHostStartable.kt:6)
        at org.jetbrains.ktor.jetty.DevelopmentHost.main(CommandLine.kt:9)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.jetbrains.ktor.application.ApplicationFeatureKt.install$default(Lorg/jetbrains/ktor/pipeline/Pipeline;Lorg/jetbrains/ktor/application/ApplicationFeature;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Ljava/lang/Object;" the class loader (instance of org/jetbrains/ktor/host/OverridingClassLoader$ChildURLClassLoader) of the current class, org/jetbrains/demo/thinkter/ApplicationKt, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/jetbrains/ktor/application/ApplicationFeatureKt, have different Class objects for the type kotlin/jvm/functions/Function1 used in the signature
        at org.jetbrains.demo.thinkter.ApplicationKt.main(Application.kt:21)
        ... 20 more
```
I still can not understand what coincides with thinkter, which leads to an error.

I thought this was related to the main class (Application.kt) package, where there is a thinkter:
`package org.jetbrains.demo.thinkter`
But using as a directory name, for example, a `demo` does not lead to an error.

**Comment by devulex** [comment]
I found a match: project directory and parameter `watch`.
Disabling automatic reload of the application `autoreload = false` helps to get around this error.
Since I was creating the application distribution for production, this solution suited me.

**Comment by maoueh** [comment]
Thanks for the tip, had the same issue and indeed getting rid of `watch` fixed the problem for me too.

How to disable `autoreload` just for production build, is it possible without creating some custom Gradle tasks? Can a specific developer application configuration file can be defined?

Possible to use environment variables in the `application.conf` to configure something?

**Comment by orangy** [comment]
http://ktor.io/servers/configuration.html

**Comment by maoueh** [comment]
Thanks for the pointer, I already saw, I'll build something around this.
