### ISSUE TITLE
Exception from FileReadChannel.

### ISSUE THREAD

**Issue by spand** [Kotlin/ktor#46]
No quite sure why it happened but should be handled somehow.

```
java.lang.IllegalArgumentException: endInclusive shouldn't be less than start but start = 0, endInclusive = -1
    at org.jetbrains.ktor.nio.FileReadChannel.<init>(FileReadChannel.kt:16)
    at org.jetbrains.ktor.nio.FileReadChannel.<init>(FileReadChannel.kt:8)
    at org.jetbrains.ktor.nio.FileReadChannelKt.asyncReadOnlyFileChannel(FileReadChannel.kt:84)
    at org.jetbrains.ktor.nio.FileReadChannelKt.asyncReadOnlyFileChannel(FileReadChannel.kt:85)
    at org.jetbrains.ktor.nio.FileReadChannelKt.asyncReadOnlyFileChannel$default(FileReadChannel.kt:85)
    at org.jetbrains.ktor.content.LocalFileContent.channel(StaticContent.kt:31)
    at org.jetbrains.ktor.content.LocalFileContent.channel(StaticContent.kt:15)
    at org.jetbrains.ktor.content.FinalContent$ChannelContent.startContent(FinalContent.kt:28)
    at org.jetbrains.ktor.host.BaseApplicationCall$1.invoke(BaseApplicationCall.kt:64)
    at org.jetbrains.ktor.host.BaseApplicationCall$1.invoke(BaseApplicationCall.kt:11)
    at org.jetbrains.ktor.pipeline.PipelineBlock.call(PipelineBlock.kt:9)
    at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:34)
    at org.jetbrains.ktor.pipeline.PipelineExecution.proceed(PipelineExecution.kt:18)
    at org.jetbrains.ktor.pipeline.AsyncKt.continuePipeline(Async.kt:104)
    at org.jetbrains.ktor.transform.TransformationSupport$transform$1$1.invoke(TransformIntercept.kt:39)
    at org.jetbrains.ktor.transform.TransformationSupport$transform$1$1.invoke(TransformIntercept.kt:11)
    at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:86)
    at org.jetbrains.ktor.pipeline.PipelineMachine.execute(PipelineMachine.kt:15)
    at org.jetbrains.ktor.transform.TransformationSupport.transform(TransformIntercept.kt:48)
    at org.jetbrains.ktor.transform.TransformationSupport.access$transform(TransformIntercept.kt:11)
    at org.jetbrains.ktor.transform.TransformationSupport$install$1$1.invoke(TransformIntercept.kt:23)
    at org.jetbrains.ktor.transform.TransformationSupport$install$1$1.invoke(TransformIntercept.kt:11)
    at org.jetbrains.ktor.pipeline.PipelineBlock.call(PipelineBlock.kt:9)
    at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:34)
    at org.jetbrains.ktor.pipeline.PipelineMachine.execute(PipelineMachine.kt:15)
    at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.run(Async.kt:23)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by orangy** [comment]
@cy6erGn0m is it fixed by mentioned commit?
