### ISSUE TITLE
java.lang.IllegalStateException: ReadListener already set

### ISSUE THREAD

**Issue by mathiasbn** [Kotlin/ktor#52]
I have a long running request (>1min). At some point the server just crashes with the following breakpoint.
Even if I just put a "thread only" suspending breakpoint in the `post` body it crashes
```
java.lang.IllegalStateException: ReadListener already set
    at org.eclipse.jetty.server.HttpInput.setReadListener(HttpInput.java:600) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
    at org.jetbrains.ktor.servlet.ServletReadChannel.read(ServletReadChannel.kt:45) ~[ktor-servlet-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.nio.AsyncReadChannelAdapterStream.read(Channels.kt:114) ~[ktor-core-0.2.3.jar:0.2.3]
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_60]
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_60]
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_60]
    at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_60]
    at java.io.Reader.read(Reader.java:140) ~[na:1.8.0_60]
    at kotlin.io.TextStreamsKt.copyTo(ReadWrite.kt:116) ~[kotlin-stdlib-1.0.5.jar:1.0.5]
    at kotlin.io.TextStreamsKt.copyTo$default(ReadWrite.kt:113) ~[kotlin-stdlib-1.0.5.jar:1.0.5]
    at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:100) ~[kotlin-stdlib-1.0.5.jar:1.0.5]
    at org.jetbrains.ktor.request.RequestContent$contentAsString$2.invoke(RequestContent.kt:11) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.request.RequestContent$contentAsString$2.invoke(RequestContent.kt:10) ~[ktor-core-0.2.3.jar:0.2.3]
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5.jar:1.0.5]
    at org.jetbrains.ktor.request.RequestContent.getContentAsString(RequestContent.kt) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.request.RequestContent.get(RequestContent.kt:37) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.request.RequestContent$computedValuesMap$2.invoke(RequestContent.kt:49) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.request.RequestContent$computedValuesMap$2.invoke(RequestContent.kt:10) ~[ktor-core-0.2.3.jar:0.2.3]
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5.jar:1.0.5]
    at org.jetbrains.ktor.request.RequestContent.getComputedValuesMap(RequestContent.kt) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.request.RequestContent.get(RequestContent.kt:38) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.host.BaseApplicationCall$parameters$2.invoke(BaseApplicationCall.kt:185) ~[ktor-hosts-common-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.host.BaseApplicationCall$parameters$2.invoke(BaseApplicationCall.kt:13) ~[ktor-hosts-common-0.2.3.jar:0.2.3]
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5.jar:1.0.5]
    at org.jetbrains.ktor.host.BaseApplicationCall.getParameters(BaseApplicationCall.kt) ~[ktor-hosts-common-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.routing.Routing.interceptor(Routing.kt:10) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.routing.Routing.access$interceptor(Routing.kt:7) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:28) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:23) ~[ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.pipeline.PipelineMachine.runAction(PipelineMachine.kt:113) [ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.pipeline.PipelineMachine.loop(PipelineMachine.kt:105) [ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:25) [ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.pipeline.PipelineMachine.execute(PipelineMachine.kt:16) [ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt:30) [ktor-core-0.2.3.jar:0.2.3]
    at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt) [ktor-core-0.2.3.jar:0.2.3]
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [na:1.8.0_60]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by cy6erGn0m** [comment]
Can't reproduce it for now. 
Btw Jetty for some reason desn't check if `HttpInput` was closed in `setReadListener` so I guess that the cause is that the connection is already closed/recycled while we are trying to read it later. I am going to make request completion more strict so channel will be closed. Most likely you will get `ClosedChannelException` instead.

**Comment by cy6erGn0m** [comment]
@mathiasbn Could you please try again with latest master?

**Comment by mathiasbn** [comment]
Sorry for the delay. Pretty much the same stacktrace 
```
java.lang.IllegalStateException: ReadListener already set
	at org.eclipse.jetty.server.HttpInput.setReadListener(HttpInput.java:600) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.jetbrains.ktor.servlet.ServletReadChannel.read(ServletReadChannel.kt:51) ~[ktor-servlet-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.nio.AsyncReadChannelAdapterStream.read(Channels.kt:114) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_60]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_60]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_60]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_60]
	at java.io.Reader.read(Reader.java:140) ~[na:1.8.0_60]
	at kotlin.io.TextStreamsKt.copyTo(ReadWrite.kt:116) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at kotlin.io.TextStreamsKt.copyTo$default(ReadWrite.kt:113) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:100) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.request.RequestContent$contentAsString$2.invoke(RequestContent.kt:11) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.request.RequestContent$contentAsString$2.invoke(RequestContent.kt:10) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.request.RequestContent.getContentAsString(RequestContent.kt) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.request.RequestContent.get(RequestContent.kt:37) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.request.RequestContent$computedValuesMap$2.invoke(RequestContent.kt:49) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.request.RequestContent$computedValuesMap$2.invoke(RequestContent.kt:10) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.request.RequestContent.getComputedValuesMap(RequestContent.kt) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.request.RequestContent.get(RequestContent.kt:38) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.host.BaseApplicationCall$parameters$2.invoke(BaseApplicationCall.kt:185) ~[ktor-hosts-common-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.host.BaseApplicationCall$parameters$2.invoke(BaseApplicationCall.kt:13) ~[ktor-hosts-common-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.host.BaseApplicationCall.getParameters(BaseApplicationCall.kt) ~[ktor-hosts-common-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.routing.Routing.interceptor(Routing.kt:10) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.routing.Routing.access$interceptor(Routing.kt:7) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:28) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:23) ~[ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.pipeline.PipelineMachine.runAction(PipelineMachine.kt:111) [ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.pipeline.PipelineMachine.loop(PipelineMachine.kt:103) [ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:25) [ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.pipeline.PipelineMachine.execute(PipelineMachine.kt:16) [ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt:30) [ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt) [ktor-core-0.2.4-MOINZ-SNAPSHOT.jar:0.2.4-MOINZ-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [na:1.8.0_60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by cy6erGn0m** [comment]
Could you please provide code so I can reproduce it?

**Comment by mathiasbn** [comment]
You just need to set a `suspend Thread` breakpoint in a post, and the call it with a 
`Content-Type: application/x-www-form-urlencoded` request.

We suspect it is a sideeffect of an issue with async servlets having a timeout of 30 seconds after which it is called again (Issue no. comming in a moment)

**Comment by cy6erGn0m** [comment]
@mathiasbn could you please confirm that the solution from PR #54 fixes the issue?

**Comment by mathiasbn** [comment]
It does.
