### ISSUE TITLE
Exception in NettyApplicationRequest.close

### ISSUE THREAD

**Issue by orangy** [Kotlin/ktor#55]
```
2016-12-07 12:06:43.196 [nioEventLoopGroup-3-1] WARN  i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: org.jetbrains.ktor.netty.NettyApplicationRequest$close$$inlined$executeInLoop$1@22adee83
java.util.NoSuchElementException: org.jetbrains.ktor.netty.BodyHandlerChannelAdapter
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1089) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:428) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at org.jetbrains.ktor.netty.NettyApplicationRequest$close$$inlined$executeInLoop$1.run(NettyApplicationRequest.kt:141) ~[classes/:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

Reproducible on Login in you-kube sample.

**Comment by orangy** [comment]
And more in the same place:
```
ERROR Application - Unhandled: POST - /login
java.lang.IndexOutOfBoundsException: index: 1024, length: 1 (expected: range(0, 1024))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1359) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1354) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1349) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:520) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:137) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:246) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:891) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at org.jetbrains.ktor.netty.BodyHandlerChannelAdapter.putTo(BodyHandlerChannelAdapter.kt:113) ~[classes/:na]
	at org.jetbrains.ktor.netty.BodyHandlerChannelAdapter.meet(BodyHandlerChannelAdapter.kt:60) ~[classes/:na]
	at org.jetbrains.ktor.netty.BodyHandlerChannelAdapter.meet$default(BodyHandlerChannelAdapter.kt:58) ~[classes/:na]
	at org.jetbrains.ktor.netty.BodyHandlerChannelAdapter.tryToMeet(BodyHandlerChannelAdapter.kt:50) ~[classes/:na]
	at org.jetbrains.ktor.netty.BodyHandlerChannelAdapter.read(BodyHandlerChannelAdapter.kt:40) ~[classes/:na]
	at org.jetbrains.ktor.nio.AsyncReadChannelAdapterStream.read(Channels.kt:114) ~[classes/:na]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_111]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_111]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_111]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_111]
	at java.io.Reader.read(Reader.java:140) ~[na:1.8.0_111]
	at kotlin.io.TextStreamsKt.copyTo(ReadWrite.kt:120) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at kotlin.io.TextStreamsKt.copyTo$default(ReadWrite.kt:113) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:100) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.request.RequestContent$contentAsString$2.invoke(RequestContent.kt:11) ~[classes/:na]
	at org.jetbrains.ktor.request.RequestContent$contentAsString$2.invoke(RequestContent.kt:10) ~[classes/:na]
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.request.RequestContent.getContentAsString(RequestContent.kt) ~[classes/:na]
	at org.jetbrains.ktor.request.RequestContent.get(RequestContent.kt:37) ~[classes/:na]
	at org.jetbrains.ktor.request.RequestContent$computedValuesMap$2.invoke(RequestContent.kt:49) ~[classes/:na]
	at org.jetbrains.ktor.request.RequestContent$computedValuesMap$2.invoke(RequestContent.kt:10) ~[classes/:na]
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.request.RequestContent.getComputedValuesMap(RequestContent.kt) ~[classes/:na]
	at org.jetbrains.ktor.request.RequestContent.get(RequestContent.kt:38) ~[classes/:na]
	at org.jetbrains.ktor.host.BaseApplicationCall$parameters$2.invoke(BaseApplicationCall.kt:188) ~[classes/:na]
	at org.jetbrains.ktor.host.BaseApplicationCall$parameters$2.invoke(BaseApplicationCall.kt:13) ~[classes/:na]
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131) ~[kotlin-stdlib-1.0.5-2.jar:1.0.5-2]
	at org.jetbrains.ktor.host.BaseApplicationCall.getParameters(BaseApplicationCall.kt) ~[classes/:na]
	at org.jetbrains.ktor.routing.Routing.interceptor(Routing.kt:10) ~[classes/:na]
	at org.jetbrains.ktor.routing.Routing.access$interceptor(Routing.kt:7) ~[classes/:na]
	at org.jetbrains.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:28) ~[classes/:na]
	at org.jetbrains.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:23) ~[classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.runAction(PipelineMachine.kt:111) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.loop(PipelineMachine.kt:103) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:25) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineExecution.proceed(PipelineExecution.kt:31) [classes/:na]
	at org.jetbrains.ktor.sessions.CookieValueSessionTracker.lookup(CookieValueSessionTracker.kt:22) [classes/:na]
	at org.jetbrains.ktor.sessions.SessionsKt$withSessions$1.invoke(Sessions.kt:59) [classes/:na]
	at org.jetbrains.ktor.sessions.SessionsKt$withSessions$1.invoke(Sessions.kt) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.runAction(PipelineMachine.kt:111) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.loop(PipelineMachine.kt:103) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:25) [classes/:na]
	at org.jetbrains.ktor.pipeline.PipelineMachine.execute(PipelineMachine.kt:16) [classes/:na]
	at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt:30) [classes/:na]
	at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt) [classes/:na]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [na:1.8.0_111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by orangy** [comment]
Obsolete
