### ISSUE TITLE
Documentation to use with Kotlin 1.1 EAP?

### ISSUE THREAD

**Issue by Jire** [Kotlin/ktor#57]
I tried to get it working with both the Netty and Jetty embedded server. I am using Ktor 0.2.4 and Kotlin 1.1-M03.

```kotlin
import org.jetbrains.ktor.application.call
import org.jetbrains.ktor.application.install
import org.jetbrains.ktor.features.DefaultHeaders
import org.jetbrains.ktor.jetty.embeddedJettyServer
import org.jetbrains.ktor.logging.CallLogging
import org.jetbrains.ktor.response.respondText
import org.jetbrains.ktor.routing.Routing
import org.jetbrains.ktor.routing.get

fun main(args: Array<String>) = embeddedJettyServer {
	install(DefaultHeaders)
	install(CallLogging)
	install(Routing) {
		get("/") {
			call.respondText("Hello, World!")
		}
	}
}.start()
```

```
2016-12-09 20:23:11.000 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @426ms
2016-12-09 20:23:11.064 [main] TRACE embedded - Starting server...
2016-12-09 20:23:11.065 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.3.13.v20161014
2016-12-09 20:23:11.126 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@69a10787{HTTP/1.1,[http/1.1, h2c, h2c-17, h2c-16, h2c-15, h2c-14]}{0.0.0.0:80}
2016-12-09 20:23:11.126 [main] INFO  org.eclipse.jetty.server.Server - Started @555ms
2016-12-09 20:23:11.126 [main] TRACE embedded - Server running.
2016-12-09 20:23:13.826 [ktor-pool-1-thread-1] ERROR embedded - null: GET - /
java.lang.IncompatibleClassChangeError: class kotlin.reflect.jvm.internal.KFunctionImpl has interface kotlin.jvm.internal.FunctionImpl as super class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_112]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_112]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_112]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_112]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_112]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_112]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_112]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_112]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_112]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_112]
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$getMembers$visitor$1.visitFunctionDescriptor(KDeclarationContainerImpl.kt:68) ~[kotlin-reflect-1.0.5-2.jar:1.0.5-2]
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$getMembers$visitor$1.visitFunctionDescriptor(KDeclarationContainerImpl.kt:52) ~[kotlin-reflect-1.0.5-2.jar:1.0.5-2]
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.FunctionDescriptorImpl.accept(FunctionDescriptorImpl.java:613) ~[kotlin-reflect-1.0.5-2.jar:1.0.5-2]
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$getMembers$2.invoke(KDeclarationContainerImpl.kt:81) ~[kotlin-reflect-1.0.5-2.jar:1.0.5-2]
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$getMembers$2.invoke(KDeclarationContainerImpl.kt:33) ~[kotlin-reflect-1.0.5-2.jar:1.0.5-2]
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:137) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:98) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:533) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:557) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:550) ~[kotlin-stdlib-1.1-M03.jar:1.1-M03]
	at kotlin.reflect.KClasses.getMemberProperties(KClasses.kt:142) ~[kotlin-reflect-1.0.5-2.jar:1.1-M03]
	at org.jetbrains.ktor.http.HttpStatusCode.<clinit>(HttpStatusCode.kt:65) ~[ktor-core-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.host.BaseApplicationCall.commit(BaseApplicationCall.kt:24) ~[ktor-hosts-common-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.host.BaseApplicationCall.handleFinalContent(BaseApplicationCall.kt:87) ~[ktor-hosts-common-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.host.BaseApplicationCall$1.invoke(BaseApplicationCall.kt:47) ~[ktor-hosts-common-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.host.BaseApplicationCall$1.invoke(BaseApplicationCall.kt:13) ~[ktor-hosts-common-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.pipeline.PipelineMachine.runAction(PipelineMachine.kt:111) [ktor-core-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.pipeline.PipelineMachine.loop(PipelineMachine.kt:103) [ktor-core-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.pipeline.PipelineMachine.proceed(PipelineMachine.kt:25) [ktor-core-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.pipeline.PipelineMachine.execute(PipelineMachine.kt:16) [ktor-core-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt:30) [ktor-core-0.2.4.jar:0.2.4]
	at org.jetbrains.ktor.pipeline.AsyncKt$executeOn$1.get(Async.kt) [ktor-core-0.2.4.jar:0.2.4]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [na:1.8.0_112]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

```

**Comment by cy6erGn0m** [comment]
You have to exclude kotlin 1.0.x (stdlib, runtime and reflect)  transitive dependencies when define ktor dependency

**Comment by holmes** [comment]
Worked for me. If you're in gradle:

```
  compile("org.jetbrains.ktor:ktor-core:$ktor_version") {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-reflect'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-runtime'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
  }
```

**Comment by orangy** [comment]
Ktor is migrated to use Kotlin 1.1.0 release version.
