### ISSUE TITLE
YouKube sample fails with NPE on login

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/ktor#95]
ktor as of commit 74819e8c6a251fe8bb5fb06647acc55aae40b9fc

Runnig Ktor::YouKube via run configuration in IntelliJ IDEA 2017.1.1, opening http://localhost:8080, then trying to log in with user "U123456" and password "P123456":

```
2017-04-21 21:35:56.822 [nettyCallPool-4-2 @coroutine#8] ERROR Application - 302 Found: POST - /login
kotlin.KotlinNullPointerException: null
	at you.kube.LoginKt$login$1$1$2.doResume(Login.kt:22)
	at you.kube.LoginKt$login$1$1$2.invoke(Login.kt)
	at you.kube.LoginKt$login$1$1$2.invoke(Login.kt)
	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:26)
```

**Comment by orangy** [comment]
Fixed
